spring.datasource.url: jdbc:mysql://localhost:3306/search_engine?allowPublicKeyRetrieval=true&amp&useSSL=false&amp&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: Tenzosix34
spring.batch.jdbc.table-prefix: search_engine
spring.jpa.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.jdbc.batch_size: 5
spring.jpa.properties.hibernate.order_inserts: true

server.port: 8080
spring.liquibase.enabled: true

url.default: /admin


useragent.name: searchEngineBot/0.1

siteconfig:
  sites:
  - url: https://www.svetlovka.ru
    name: svetlovka
  - url: https://et-cetera.ru
    name: et-cetera

spring:
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
